### ISSUE TITLE
Create JWT unhandled exception

### ISSUE THREAD

**Issue by DblTS** [WebFlight/JWT#4]
It seems something is wrong with the libraries and I'm unsure where to continue looking.
I've removed other versions of the commons-codec jar file so that only 1.11 remains and validated the java path. I can't reproduce it in an empty 7.19 project, so it must be clashing somewhere. Any suggestions on where to look? Thnx.

`Error in execution of monitored action 'RegularClientAction' (execution id: 1542028273892-15, execution type: CLIENT)

--------

java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64URLSafeString([B)Ljava/lang/String;
	at com.auth0.jwt.JWTCreator.sign(JWTCreator.java:330)
	at com.auth0.jwt.JWTCreator.access$100(JWTCreator.java:24)
	at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:311)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:132)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:1)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:79)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:57)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:55)
	at com.mendix.basis.actionmanagement.ActionManagerBase$1.execute(ActionManagerBase.java:150)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:155)
	at com.mendix.basis.component.InternalCoreBase.execute(InternalCoreBase.java:414)
	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:56)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:201)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:157)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:79)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:57)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:55)
	at com.mendix.basis.actionmanagement.ActionManagerBase$1.execute(ActionManagerBase.java:150)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:155)
	at com.mendix.basis.component.InternalCoreBase.executeSync(InternalCoreBase.java:492)
	at com.mendix.modules.microflowengine.actions.SubMicroflowAction.execute(SubMicroflowAction.scala:51)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:201)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:157)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:79)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:57)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:55)
	at com.mendix.basis.actionmanagement.ActionManagerBase$1.execute(ActionManagerBase.java:150)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:155)
	at com.mendix.basis.component.InternalCoreBase.execute(InternalCoreBase.java:383)
	at com.mendix.basis.component.InternalCoreBase.execute(InternalCoreBase.java:398)
	at com.mendix.webui.actions.client.ExecuteMicroflowAction.runMicroflow(ExecuteMicroflowAction.scala:88)
	at com.mendix.webui.actions.client.ExecuteMicroflowAction.apply(ExecuteMicroflowAction.scala:36)
	at com.mendix.webui.actions.client.ExecuteMicroflowAction.apply(ExecuteMicroflowAction.scala:19)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$4(RegularClientAction.scala:46)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState(StateHandling.scala:29)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState$(StateHandling.scala:20)
	at com.mendix.webui.actions.client.RegularClientAction.withState(RegularClientAction.scala:21)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$3(RegularClientAction.scala:44)
	at scala.util.Try$.apply(Try.scala:209)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2(RegularClientAction.scala:44)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2$adapted(RegularClientAction.scala:42)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.$anonfun$inContext$4(ContextHandling.scala:41)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at com.mendix.basis.actionmanagement.IMonitoredAction$$anon$1.execute(IMonitoredAction.scala:47)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.IMonitoredAction.monitor(IMonitoredAction.scala:49)
	at com.mendix.basis.actionmanagement.IMonitoredAction.monitor$(IMonitoredAction.scala:25)
	at com.mendix.webui.requesthandling.helpers.ContextHandling$ClientMonitoredAction.monitor(ContextHandling.scala:49)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:41)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:27)
	at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:21)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:24)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:19)
	at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:21)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$1(RegularClientAction.scala:42)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest(ProfileHandling.scala:14)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest$(ProfileHandling.scala:10)
	at com.mendix.webui.actions.client.RegularClientAction.profileRequest(RegularClientAction.scala:21)
	at com.mendix.webui.actions.client.RegularClientAction.execute(RegularClientAction.scala:39)
	at com.mendix.webui.requesthandling.ClientRequestHandler.handleAction(ClientRequestHandler.scala:122)
	at com.mendix.webui.requesthandling.ClientRequestHandler.processRequest(ClientRequestHandler.scala:99)
	at com.mendix.externalinterface.connector.RequestHandler.doProcessRequest(RequestHandler.java:40)
	at com.mendix.external.connector.MxRuntimeConnector$1.execute(MxRuntimeConnector.java:72)
	at com.mendix.external.connector.MxRuntimeConnector$1.execute(MxRuntimeConnector.java:69)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.external.connector.MxRuntimeConnector.processRequest(MxRuntimeConnector.java:75)
	at com.mendix.basis.impl.MxRuntimeImpl.processRequest(MxRuntimeImpl.java:873)
	at com.mendix.m2ee.appcontainer.server.handler.RuntimeHandler.service(RuntimeHandler.java:42)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by mennodehaas** [comment]
Did you try to clean the deployment directory?

**Comment by DblTS** [comment]
Yes, multiple times.
I'm currently putting all the appstore modules I have in my project, also in my testproject, and see if I can get it to fail again somehow.

**Comment by mennodehaas** [comment]
https://stackoverflow.com/questions/7688644/java-lang-nosuchmethoderror-org-apache-commons-codec-binary-base64-encodebase64:

> This prove to all jars which are using early version of common-codec internally and at the same time someone using common-codec explicitly on classpath too.

**Comment by mennodehaas** [comment]
@DblTS please let me know if you can find anything. I have to admit I had similar issues in the past with other modules and sometimes dependency issues are very hard to solve.

**Comment by DblTS** [comment]
So far, no luck. I'm still looking!

**Comment by DblTS** [comment]
Found it! Turns out it was this one:
org.apache.servicemix.bundles.commons-codec-1.3.0
I still haven't figured out which appstore module (probably an old one) dragged this one in..

**Comment by DblTS** [comment]
And, thanks for your help in pointing me in the right direction :) Anti-tunnelvisie 👍

**Comment by mennodehaas** [comment]
Thanks! I'm happy you found the issue. I will add it to the Readme.md for the next release. Are you happy with the module? Do you have tips about what to improve? Would be nice if you leave review in the App Store.

**Comment by DblTS** [comment]
No, we're quite happy with it! I'll leave a review in the app store 👍
