### ISSUE TITLE
Error in executing Java actions of JWT module

### ISSUE THREAD

**Issue by mwbouwkamp-mendix** [WebFlight/JWT#8]
A few weeks/months ago, I was using the JWT module and it was working like a charm. However, I currently get errors when executing the Java actions, for example  the Generate JWT action. I get the following three consecutive errors in my Mendix console:

### First one (Lognode ActionManager)

**Message:**
Error in execution of monitored action '{"name":"PublishedServices.POST_Login","type":"Microflow"}' (execution id: b5a90579-c89a-45c2-bf79-d765903935ca, execution type: CUSTOM)

**Stack trace:**
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:619)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:528)
	at com.auth0.jwt.JWTCreator.<init>(JWTCreator.java:33)
	at com.auth0.jwt.JWTCreator.<init>(JWTCreator.java:24)
	at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:311)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:152)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:40)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	...

### Second one (Lognode ActionManager)

**Message:**
Error in execution of monitored action '/rest/MYAPP/v1/login' (execution id: 1a9f8250-e004-4781-a992-21c62b5bcf81, execution type: UNKNOWN)

**Stack trace:**
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:619)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:528)
	at com.auth0.jwt.JWTCreator.<init>(JWTCreator.java:33)
	at com.auth0.jwt.JWTCreator.<init>(JWTCreator.java:24)
	at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:311)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:152)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:40)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	...

### Third one (LogNode M2EE)

**Messsage:**
An unhandled error occurred in the MxRuntime.

**Stack trace:**
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:619)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:528)
	at com.auth0.jwt.JWTCreator.<init>(JWTCreator.java:33)
	at com.auth0.jwt.JWTCreator.<init>(JWTCreator.java:24)
	at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:311)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:152)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:40)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	...

Hope you can help!

**Comment by mennodehaas** [comment]
You might have the incorrect version of Jackson dependencies in your userlib folder or other conflicting versions introduced by other App Store modules.
![image](https://user-images.githubusercontent.com/24918726/89264101-a39e7080-d632-11ea-9ebb-de8190519027.png)

**Comment by mwbouwkamp-mendix** [comment]
It turned out to be a conflict with com.fasterxml.jackson.core.jar. Thanks for your help!

**Comment by mennodehaas** [comment]
@MWBtimeseries thanks! Would be nice if you could rate the module in the Mendix App Store.

**Comment by Capital75** [comment]
@MWBtimeseries I'm running into exactly this issue. Could you share how you resolved the conflict on the com.fasterxml.jackson.core.jar file?

**Comment by mwbouwkamp-mendix** [comment]
@Capital75 I ended up deleting the duplicate library files. If I remember correctly, I needed to do some fixes afterwards by reimporting some modules, though.
