### ISSUE TITLE
Error in executing Java actions

### ISSUE THREAD

**Issue by Capital75** [WebFlight/JWT#9]
Hi Menno!
I'd like to implement the JWT module in a 8.14.1 mx project.
On a new, clean project, it works perfectly.
However, on my existing project, it throws errors at executing the Java actions.
To make the new and the existing project more comparable, I've imported all the app store modules used in the existing project, in the new project. After that, I've copied the userlib files from the new project to the existing one. To no avail: the module in the new project keeps working, but the error keeps showing up in the existing project. Do you know where to search for a solution?
Kind regards,
Marieke

Error message 1 - Actionmanager:
Error in execution of monitored action 'RegularClientAction' (execution id: 1604649864191-11, execution type: CLIENT)
Stack trace:
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:619)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:528)
	at com.auth0.jwt.JWTCreator.<init>(JWTCreator.java:33)
	at com.auth0.jwt.JWTCreator.<init>(JWTCreator.java:24)
	at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:311)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:152)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:40)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
...

Error message 2 - M2EE:
An unhandled error occurred in the MxRuntime.
Stack trace:
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:619)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:528)
	at com.auth0.jwt.JWTCreator.<init>(JWTCreator.java:33)
	at com.auth0.jwt.JWTCreator.<init>(JWTCreator.java:24)
	at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:311)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:152)
	at jwt.actions.GenerateJWT.executeAction(GenerateJWT.java:40)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
...

Error message 3 - Client:
An error occurred while executing an action of Beheer.Conversies.actionButton3: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

I do have different versions of jackson-annotations, jackson-core and jackson-databind, but if I only keep the 2.10.0.pr3 versions, the error is the same
![jacksonVersions](https://user-images.githubusercontent.com/58769076/98342766-2e678080-2011-11eb-822d-1e39485344b6.jpg)

**Comment by Capital75** [comment]
Fixed by updating the userlibrary.
